heat_template_version: 2016-04-08
resources:
  port01:
      type: ECL::Network::Port
      properties:
          network_id: d6a2215a-da0a-4599-a775-df8d9e07fa93
  vm01:
    type: ECL::Compute::Server
    properties:
      name: vm01
      image: ad936ae4-2983-4f23-9187-e47e82cb2725
      flavor: "1CPU-4GB"
      availability_zone: zone1-groupb
      user_data_format: RAW
      user_data:
          str_replace:
              template: |
                  #!/bin/bash
                  echo "Port id is $port_id" > /tmp/hoge.txt
              params:
                  $port_id: { get_resource: port01 }
      networks:
        - uuid: d6a2215a-da0a-4599-a775-df8d9e07fa93
